server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/api-demo"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "T0qBfSj1e9kj+/96Xy4Xo74+ZC256HOMIV7pJhr9VL/1bviHiYUOqm9oorDmnThe"